# Generated by Django 2.2.4 on 2019-08-11 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_read_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='read_time',
            field=models.CharField(default='0 minutes read', max_length=100),
        ),
    ]
