# Generated by Django 2.2.4 on 2019-08-11 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_images'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Images',
        ),
    ]
